# Generated by Django 3.2 on 2022-03-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0004_alter_profil_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profils  utilisateur'},
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/usericon.png', null=True, upload_to='avatars/'),
        ),
    ]
