# Generated by Django 3.2 on 2022-05-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userAccount', '0005_auto_20220318_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='gender',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='idNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='idType',
            field=models.CharField(blank=True, choices=[('cni', "Carte Nationale d'identité"), ('passeport', 'Passeport'), ('attestation', 'Attestation d\\identité')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profils', to='auth.group'),
        ),
    ]
