# Generated by Django 3.2 on 2022-05-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_auto_20220524_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='idType',
            field=models.CharField(blank=True, choices=[('cni', "Carte Nationale d'identité"), ('passeport', 'Passeport'), ('attestation', "Attestation d'identité")], max_length=50, null=True),
        ),
    ]
