# Generated by Django 3.2 on 2022-05-25 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0008_auto_20220525_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
