# Generated by Django 3.2 on 2023-09-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0012_alter_profil_id_delivered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='id_delivered_at',
        ),
    ]
