# Generated by Django 3.2 on 2023-09-20 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0013_remove_profil_id_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='id_delivered_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
