# Generated by Django 3.2 on 2023-09-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0014_profil_id_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
