# Generated by Django 3.2 on 2023-09-20 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0015_profil_place_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='domicile',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='father',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='id_delivered_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='id_delivered_place',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='job',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='mother',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nationnalite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='place_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
