# Generated by Django 3.2 on 2025-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0016_auto_20230920_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='father',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='mother',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
