# Generated by Django 3.2 on 2022-05-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_booking_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number',
        ),
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('en attente', 'En attente'), ('payée', 'Payée'), ('archivée', 'Archivée')], max_length=15),
        ),
    ]
