# Generated by Django 3.2 on 2022-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20220527_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkIn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkOut',
            field=models.DateTimeField(),
        ),
    ]
