# Generated by Django 3.2 on 2022-05-31 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0009_alter_profil_dob'),
        ('hotel', '0004_auto_20220528_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='userAccount.profil')),
            ],
            options={
                'verbose_name': 'depense',
                'verbose_name_plural': 'depenses',
            },
        ),
    ]
