# Generated by Django 3.2 on 2022-06-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
