# Generated by Django 3.2 on 2022-07-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('visa', 'Visa'), ('devise', 'Devise')], default='espece', max_length=15),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('en attente', 'En attente'), ('confirmée', 'Confirmée'), ('annulée', 'Annulée')], default='en attente', max_length=15),
        ),
    ]
