# Generated by Django 3.2 on 2023-08-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_auto_20220712_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pj', 'pj'), ('dj', 'dj'), ('dt', 'dt'), ('dp', 'dp'), ('paye', 'Payée'), ('archivée', 'Archivée')], max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('os', 'Occupée Sale'), ('og', 'Occupée Gratuite'), ('op', 'Occupée Propre'), ('lp', 'Libre Propre'), ('ls', 'Libre Sale'), ('nettoyage', 'Nettoyage')], default='lp', max_length=10),
        ),
    ]
