# Generated by Django 3.2 on 2025-06-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20230913_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amountPaid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('fixe', 'Fixe'), ('pourcentage', 'Pourcentage')], default='fixe', max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Terminée')], max_length=15),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('ongoing', 'En cours'), ('completed', 'Terminée')], max_length=15),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pj', 'Payé jour'), ('dj', 'Dette jour'), ('dt', 'Dette totale'), ('dp', 'Dette payée')], max_length=15)),
                ('payment', models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('visa', 'Visa'), ('devise', 'Devise')], default='espece', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.booking')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
            },
        ),
    ]
