# Generated by Django 3.2 on 2025-06-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20250613_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amountDue',
            field=models.IntegerField(default=0),
        ),
    ]
