# Generated by Django 3.2 on 2025-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_booking_amountdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('visa', 'Visa'), ('devise', 'Devise')], default='espece', max_length=15),
        ),
    ]
