# Generated by Django 3.2 on 2025-06-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_reservation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='type',
        ),
    ]
